
version: '3.9'

services:

  python:
    image: python:3-alpine
    network_mode: service:mongodb
    volumes:
    - ../volume/:/data/
  
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mtg_user
      MONGO_INITDB_ROOT_PASSWORD: mtg_pass
    volumes:
    - ../volume/db/mongodb/data:/data/db
    ports:
    - 27017:27017
  