# Use root/example as user/password credentials
version: "3.8"
services:
  mongodb:
   image: mongo:4.4.6
   container_name: mongodb
   environment:
   - PUID=1000
   - PGID=1000
   - MONGO_INITDB_ROOT_USERNAME=mtg_user
   - MONGO_INITDB_ROOT_PASSWORD=mtg_pass
   #volumes:
   #- /media/datalab/fcoelho/StudyDev/Python/mtg_openai/mongodb/data:/data/db
   ports:
   - 27017:27017
   restart: unless-stopped
